# Generated by Django 5.0.6 on 2024-05-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0004_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
