# Generated by Django 5.0.6 on 2024-05-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0007_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
