# Generated by Django 5.0.6 on 2024-05-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0010_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='end_date',
            new_name='ended_year',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='start_date',
            new_name='started_year',
        ),
    ]
