# Generated by Django 5.0.6 on 2024-05-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0011_rename_end_date_education_ended_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='ended_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='started_year',
            field=models.IntegerField(),
        ),
    ]
