# Generated by Django 5.0.6 on 2024-05-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0012_alter_education_ended_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
