# Generated by Django 5.0.6 on 2024-05-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobusers', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
