# Generated by Django 5.0.6 on 2024-05-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobusers', '0006_jobapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job_application',
            new_name='job',
        ),
    ]
