# Generated by Django 5.0.6 on 2024-05-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobusers', '0007_rename_job_application_jobapplication_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
